#!/bin/sh -e
#help: Install iberian keyboard.
. getsrc-vault
. getsrc-cached
install_keyboard() {
    local u t f
    u="https://ibers.cat/uniedit-iberian.tcl"
    t="/usr/local/bin/iberian-keyboard"
    if test -e "${t}"; then return 0; fi
    f="$(getsrc_vault -n uniedit-iberian.tcl getsrc_cached "${u}")"
    test -n "${f}"
    sudo cp -v "${f}" "${t}"
    sudo chmod -v +x "${t}"
}
if test @"$(basename "$0")" = @"install-keyboard"; then
    install_keyboard
fi
