#!/bin/sh -e
#help: Install iberian fonts.
. getsrc-vault
. getsrc-cached
install_fonts() {
    local u t f
    u="https://ibers.cat/iberian.ttf"
    t="/usr/share/fonts/TTF/iberian.ttf"
    if test -e "${t}"; then return 0; fi
    f="$(getsrc_vault -n iberian-font getsrc_cached "${u}")"
    test -n "${f}"
    sudo mkdir -p -v "$(dirname "${t}")"
    sudo cp -v "${f}" "${t}"
}
if test @"$(basename "$0")" = @"install-fonts"; then
    install_fonts
fi
