#!/bin/sh -e
##:
#h: Usage: lsetup-fonts-iberian -i : Install iberian font.
##:
#help: Install iberian fonts.
##:
. getsrc-vault
. getsrc-cached
lsetup_fonts_iberian() {
    local u t f
    u="https://ibers.cat/iberian.ttf"
    t="/usr/share/fonts/TTF/iberian.ttf"
    if test -e "${t}"; then return 0; fi
    f="$(getsrc_vault -n iberian-font getsrc_cached "${u}")"
    test -n "${f}"
    sudo mkdir -p -v "$(dirname "${t}")"
    sudo cp -v "${f}" "${t}"
}
if test @"$(basename "$0")" = @"lsetup-fonts-iberian";then
    case "${1}" in
        ''|-h|--help) sed -n 's/^ *#h: \{0,1\}//p' "$0" ;;
        -*i*)         lsetup_fonts_iberian "$@"; exit 0 ;;
    esac
fi
